import { query } from '../db/client.js'
import { emitProgress } from './progress.js'
import { mapsService } from '../services/maps.js'
import { musicBrainzService } from '../services/musicbrainz.js'
import { spotifyService } from '../services/spotify.js'
import type { JobSettings, CityResult } from '../shared/types.js'

export async function runPlaylistJob(jobId: string, userId: string) {
  const setStatus = async (status: string, extra: Partial<Record<string, unknown>> = {}) => {
    await query('UPDATE jobs SET status = $1, updated_at = NOW() WHERE id = $2', [status, jobId])
    emitProgress({ jobId, status: status as any, message: extra.message as string ?? status, ...extra })
  }

  try {
    const [job] = await query<{ origin: string; destination: string; settings: JobSettings }>(
      'SELECT origin, destination, settings FROM jobs WHERE id = $1', [jobId]
    )
    const settings = job.settings

    // 1. Get route from Google Maps
    await setStatus('routing', { message: 'Getting route...' })
    const route = await mapsService.getRoute(job.origin, job.destination)

    // 2. Sample points and reverse-geocode to city names
    await setStatus('geocoding', { message: 'Finding cities along the route...' })
    const cities = await mapsService.extractCities(route, settings.samplingIntervalKm)
    emitProgress({ jobId, status: 'geocoding', message: `Found ${cities.length} places`, citiesFound: cities.length })

    // 3. Look up artists for each city
    await setStatus('artists', { message: 'Looking up local artists...' })
    const cityResults: CityResult[] = []
    let artistsFound = 0

    for (const [i, city] of cities.entries()) {
      const artists = await musicBrainzService.getArtistsForCity(city.name, settings)
      const result: CityResult = { name: city.name, routeOrder: i, mbid: city.mbid, artists }
      cityResults.push(result)
      artistsFound += artists.length

      await query(
        'INSERT INTO job_cities (job_id, city_name, route_order, mbid, artists) VALUES ($1, $2, $3, $4, $5)',
        [jobId, city.name, i, city.mbid, JSON.stringify(artists)]
      )

      emitProgress({ jobId, status: 'artists', message: `${city.name}: ${artists.length} artist(s)`, artistsFound })
    }

    // 4. Create Spotify playlist and add tracks
    await setStatus('spotify', { message: 'Building your Spotify playlist...' })
    const [user] = await query<{ access_token: string; refresh_token: string; token_expires_at: string }>(
      'SELECT access_token, refresh_token, token_expires_at FROM users WHERE id = $1', [userId]
    )

    const token = await spotifyService.getValidToken(user)
    const [spotifyUser] = await query<{ spotify_id: string }>('SELECT spotify_id FROM users WHERE id = $1', [userId])

    const playlist = await spotifyService.createPlaylist(
      token,
      spotifyUser.spotify_id,
      `${job.origin} → ${job.destination}`,
      `Artists from along your roadtrip route. Generated by Roadtrip Playlist.`,
      settings.playlistVisibility === 'public'
    )

    let tracksAdded = 0
    const orderedCities = settings.playlistOrder === 'shuffle'
      ? cityResults.sort(() => Math.random() - 0.5)
      : cityResults

    for (const city of orderedCities) {
      for (const artist of city.artists.slice(0, settings.maxArtistsPerCity)) {
        if (!artist.spotifyId) continue
        const trackUris = await spotifyService.getTopTrackUris(token, artist.spotifyId, settings.tracksPerArtist)
        if (trackUris.length) {
          await spotifyService.addTracks(token, playlist.id, trackUris)
          tracksAdded += trackUris.length
        }
      }
    }

    await query(
      'UPDATE jobs SET status = $1, spotify_playlist_id = $2, spotify_playlist_url = $3, updated_at = NOW() WHERE id = $4',
      ['complete', playlist.id, playlist.external_urls.spotify, jobId]
    )
    emitProgress({ jobId, status: 'complete', message: 'Playlist ready!', tracksAdded })

  } catch (err: any) {
    await query('UPDATE jobs SET status = $1, error = $2, updated_at = NOW() WHERE id = $3',
      ['failed', err.message, jobId])
    emitProgress({ jobId, status: 'failed', message: err.message })
  }
}
