import { query } from '../db/client.js'
import { emitProgress } from './progress.js'
import { mapsService } from '../services/maps.js'
import { musicBrainzService } from '../services/musicbrainz.js'
import { spotifyService } from '../services/spotify.js'
import type { JobSettings, CityResult } from '../../../shared/types.js'

export async function runPlaylistJob(jobId: string, userId: string) {
  const setStatus = async (status: string, message: string, extra: Record<string, unknown> = {}) => {
    await query('UPDATE jobs SET status = $1, updated_at = NOW() WHERE id = $2', [status, jobId])
    emitProgress({ jobId, status: status as any, message, ...extra })
  }

  try {
    const [job] = await query<{ origin: string; destination: string; settings: JobSettings }>(
      'SELECT origin, destination, settings FROM jobs WHERE id = $1', [jobId]
    )
    if (!job) throw new Error(`Job ${jobId} not found`)

    const settings = job.settings

    // 1. Get route from Google Maps
    await setStatus('routing', 'Getting route...')
    const route = await mapsService.getRoute(job.origin, job.destination)

    // 2. Sample points and reverse-geocode to city names
    await setStatus('geocoding', 'Finding cities along the route...')
    const cities = await mapsService.extractCities(route, settings.samplingIntervalKm)
    emitProgress({ jobId, status: 'geocoding', message: `Found ${cities.length} places`, citiesFound: cities.length })

    if (cities.length === 0) {
      throw new Error(
        'No towns or cities could be identified along this route. ' +
        'Try reducing the sampling interval in settings, or check that your origin and destination are correct.'
      )
    }

    // 3. Look up artists for each city
    await setStatus('artists', 'Looking up local artists...')
    const cityResults: CityResult[] = []
    let artistsFound = 0

    // Shared across all cities in this job — prevents duplicate Spotify API
    // calls for the same artist name appearing near multiple cities on the route
    const spotifySearchCache = new Map<string, any>()

    for (const [i, city] of cities.entries()) {
      const artists = await musicBrainzService.getArtistsForCity(city.name, settings, spotifySearchCache)
      const result: CityResult = { name: city.name, routeOrder: i, mbid: city.mbid, artists }
      cityResults.push(result)
      artistsFound += artists.length

      await query(
        'INSERT INTO job_cities (job_id, city_name, route_order, mbid, artists) VALUES ($1, $2, $3, $4, $5)',
        [jobId, city.name, i, city.mbid, JSON.stringify(artists)]
      )

      emitProgress({ jobId, status: 'artists', message: `${city.name}: ${artists.length} artist(s)`, artistsFound })
    }

    // If no artists found at all, complete the job but flag it clearly
    if (artistsFound === 0) {
      await query(
        'UPDATE jobs SET status = $1, updated_at = NOW() WHERE id = $2',
        ['complete', jobId]
      )
      emitProgress({
        jobId,
        status: 'complete',
        message: 'No artists found along this route. Try adjusting your settings or choosing a different route.',
        tracksAdded: 0,
      })
      return
    }

    // 4. Create Spotify playlist and add tracks
    await setStatus('spotify', 'Building your Spotify playlist...')

    const [user] = await query<{ id: string; access_token: string; refresh_token: string; token_expires_at: string; spotify_id: string }>(
      'SELECT id, access_token, refresh_token, token_expires_at, spotify_id FROM users WHERE id = $1', [userId]
    )
    if (!user) throw new Error('User not found')

    const token = await spotifyService.getValidToken(user)

    const playlist = await spotifyService.createPlaylist(
      token,
      user.spotify_id,
      `${job.origin} → ${job.destination}`,
      `Artists from along your road trip. Generated by Roadtrip Playlist.`,
      settings.playlistVisibility === 'public'
    )

    let tracksAdded = 0
    const orderedCities = settings.playlistOrder === 'shuffle'
      ? [...cityResults].sort(() => Math.random() - 0.5)
      : cityResults

    for (const city of orderedCities) {
      for (const artist of city.artists.slice(0, settings.maxArtistsPerCity)) {
        if (!artist.spotifyId) continue
        const trackUris = await spotifyService.getTopTrackUris(token, artist.spotifyId, settings.tracksPerArtist)
        if (trackUris.length) {
          await spotifyService.addTracks(token, playlist.id, trackUris)
          tracksAdded += trackUris.length
        }
      }
    }

    const summary = tracksAdded === 0
      ? 'Playlist created but no tracks could be added — artists were found but none matched on Spotify.'
      : `Playlist ready — ${tracksAdded} track${tracksAdded === 1 ? '' : 's'} added.`

    await query(
      `UPDATE jobs
       SET status = $1, spotify_playlist_id = $2, spotify_playlist_url = $3, updated_at = NOW()
       WHERE id = $4`,
      ['complete', playlist.id, playlist.external_urls.spotify, jobId]
    )
    emitProgress({ jobId, status: 'complete', message: summary, tracksAdded })

  } catch (err: any) {
    await query(
      'UPDATE jobs SET status = $1, error = $2, updated_at = NOW() WHERE id = $3',
      ['failed', err.message, jobId]
    )
    emitProgress({ jobId, status: 'failed', message: err.message })
  }
}
